In [1]:
l1, l2, l3 = 1, 2, -3

In [2]:
import numpy as np

Linear Weighted combination

In [3]:
v1 = np.array([4,5,1]).reshape(3,1)
v2 = np.array([-4, 0, -4]).reshape(3,1)
v3 = np.array([1,3,2]).reshape(3,1)

In [4]:
v1 = np.array([4,5,1])
v2 = np.array([-4, 0, -4])
v3 = np.array([1,3,2])
np.column_stack((v1,v2,v3))

array([[ 4, -4,  1],
       [ 5,  0,  3],
       [ 1, -4,  2]])

In [5]:
w = l1*v1 + l2*v2 + l3*v3
w

array([ -7,  -4, -13])

In [7]:
# exercise 1

scalars = [l1, l2, l3]
vectors = [v1, v2, v3]

In [8]:
linear_comibnation = np.zeros(len(v1))

In [10]:
for i,j in zip(scalars, vectors):
    linear_comibnation += i * j
linear_comibnation

array([-14.,  -8., -26.])